### ISSUE TITLE
可以加个qq请教一下问题么？

### ISSUE THREAD

**Issue by zcswdt** [flierd/videoLogo#1]
您好，我也在做视频logo检测，想加个qq请教您一下问题，非常感谢！

**Comment by flierd** [comment]
Sorry I don't speak your language and google translate don't help.
What do you mean by "qq"?
The code I wrote is not for detection, it is to add a whatermark in a video, I don't know much about AI...
Can you ask in english?

> 您好，我也在做视频logo检测，想加个qq请教您一下问题，非常感谢！

**Comment by zcswdt** [comment]
> Sorry I don't speak your language and google translate don't help.
> What do you mean by "qq"?
> The code I wrote is not for detection, it is to add a whatermark in a video, I don't know much about AI...
> Can you ask in english?

Sorry for not being able to communicate with you in English. qq means a communication software, similar to WeChat and Facebook. I read your code, and there are some doubts in it. I understand that you are adding a logo to the video. The readme does not seem to describe the use of each code in detail. I have the following questions for you:
1. You add a logo to each frame of the video and then synthesize the video. If this is the case, the sound of the video will be lost. How did you deal with it?
2. You extract each frame of the video as a picture. Why is there an interval of 0.5s? Shouldn't each frame be extracted?
https://github.com/flierd/videoLogo/blob/12185e9b796c6a7f06b400e449d4c37a7f717f6c/test.py#L10
3. What is the function of the main.py file?
Looking forward to your reply, thank you！




> 
> > 您好，我也在做视频logo检测，想加个qq请教您一下问题，非常感谢！

**Comment by flierd** [comment]
Yes, the code it's a very early code, it still a mess! But here go the answers.
1) the sound: I did the sound.py file, it extract the audio of the original video and using the a command call ffmpeg add it to the video with the logo, it was the simple way I found.
2) the framerate is just doing nothing, i forgot to delete it from the code
3)The main.py: I will put the starting point to the GUI, but i did not started it yet.
I will update the readme when the project is more functional.
most of the code is a compilation of codes I found in diferent places, and the part that add the logo will be chaged to use other
pyton module (I think pillow is easier than cv)
if you take a look in my other project "carimbadorqt" you will see something that I will use here.

**Comment by zcswdt** [comment]
> Yes, the code it's a very early code, it still a mess! But here go the answers.
> 
> 1. the sound: I did the sound.py file, it extract the audio of the original video and using the a command call ffmpeg add it to the video with the logo, it was the simple way I found.
> 2. the framerate is just doing nothing, i forgot to delete it from the code
>    3)The main.py: I will put the starting point to the GUI, but i did not started it yet.
>    I will update the readme when the project is more functional.
>    most of the code is a compilation of codes I found in diferent places, and the part that add the logo will be chaged to use other
>    pyton module (I think pillow is easier than cv)
>    if you take a look in my other project "carimbadorqt" you will see something that I will use here.

Thank you for your reply. I read the sound.py file. The first ffmpeg command can extract the sound of the video, so it brings a new problem for me. I need to cut the end of the video and then synthesize the video. In this case, there will be an extra part of the sound of the synthesized video. Do you have a good way to solve the problem of redundant audio?

**Comment by flierd** [comment]
well for my use case it was not necessary, but I found this code in a forum some time ago
`from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
ffmpeg_extract_subclip("video1.mp4", start_time, end_time, targetname="test.mp4")`
you execute this in the resulting video with the extra part of the audio an put in the 'end_time' the part you want to cut
try it, It uses another module, moviepy
or you could take a look at the parameters of the ffmpeg, the answear at this link seems to work https://stackoverflow.com/questions/55668539/how-to-extract-an-audio-part-from-a-mp4-using-ffmpeg
you just change the first command call from the sound.py
